# Generated by Django 4.0.3 on 2022-06-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalist', '0002_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'subcategory')},
        ),
    ]
