# Generated by Django 4.0.3 on 2022-06-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalist', '0004_alter_category_name_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'subcategory', 'name')},
        ),
    ]
